language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: mvn compile test
install: true
branches:
  only:
    - master
notifications:
  irc: 
    channels: 
      - 'irc.esper.net#FearFree'
    on_success: always
    on_failure: always
    
