#Configuration file for WhoBannedMe.

#Minimum number of bans before triggering message to players with whobannedme.notify
minimum-bans: 3

#Maximum bans allowed to connect.  Anyone with more bans than this will not be able to connect.
#Set to -1 to disable this feature
maximum-bans: 10

#Message to send to players that try to connect, but have too many bans.
maximum-bans-message: Too many bans!

#Output scan results to console?
console-output: false

#Debug mode.  This will output lots of text to the console.
debug-mode: false

#Check for updates?
update-check: true
