#Comments here

#Maximum number of bans player can have and still login.
max-bans: 3

#Output scan results to console?
console-output: false

#Debug mode.  This will output lots of text to the console.
debug-mode: true
