#Configuration file for WhoBannedMe.

#Minimum number of bans before triggering message to players with whobannedme.notify
minimum-bans: 3

#Output scan results to console?
console-output: false

#Debug mode.  This will output lots of text to the console.
debug-mode: true
