name: WhoBannedMe
main: me.whobanned.WhoBannedMe
version: DevBuild
author: FearFree

permissions:
    whobannedme.exempt:
        description: Allows bypassing the ban check on login
        default: op
    
    whobannedme.notify:
        description: Allows users to see warning when bans are found
        default: false
        
    whobannedme.notify.all:
        description: Allows users to see all bans found, regardless of minimum-ban setting
        default: op
        
    whobannedme.lookup:
        description: Allows usage of /whobanned <playername>
        default: op
        
    whobannedme.lookup.details:
        description: Allows usage of /whobanned details <playername>

commands:
    whobanned:
        desciption: Used to look up a players ban history
        usage: /whobanned <username>
        permission: whobannedme.lookup
        
    whobanned details:
        description: Get detailed ban history report
        usage: /whobanned details <username>
        permission: whobanned.lookup.details
